density_map_name: '27094'
input_data_dir: '/media/ray-suen/TRANSCEND1/huei/Cryo2Struct2/input' # provide absolute path of input directory
amino_checkpoint: '/media/ray-suen/TRANSCEND1/huei/Cryo2Struct2/models/amino_acid_type.ckpt' # provide absolute path of amino acid checkpoint
atom_checkpoint: '/media/ray-suen/TRANSCEND1/huei/Cryo2Struct2/models/atom_type.ckpt' # provide absolute path of atom checkpoint
confidence_score_models: '/media/ray-suen/TRANSCEND1/huei/Cryo2Struct2/models' # provide absolute path of models directory
infer_run_on: 'gpu' # options- cpu or gpu
infer_on_gpu: 0
threshold: 0.4 # threshold for picking carbon alpha atoms
clustering_threshold: 3 # clustering proximity
use_sequence: 'full' # options- full or atomic_chain
std_lambda: 10
reverse_seq: False # 設定胺基酸序列的輸出要倒序還是正序(正序為F 反序為N)

split_mod: 2 # 1是取最大機率值  2是取0.4當作標準
CA_C_DIST: 2  # C–CA 最大允許距離
CA_N_DIST: 2  # N–CA 最大允許距離
